mysite/demo/urls.py
from django.conf.urls import url
from . import views
app_name='demo'
urlpatterns=[
	url(r'^index/$',views.index),
	url(r'^$',views.index,name='index'),
	url(r'^login/$',views.login,name='login'),
	url(r'^system/$',views.system,name='system'),
	url(r'^logout/$',views.logout,name='logout'),
	url(r'^craptimer/$',views.craptimer,name='craptimer'),
	url(r'^crap/$',views.crap,name='crap'),
	url(r'^crap_begin/$',views.crap_begin,name='crap_begin'),
	url(r'^upweb/$',views.upweb,name='upweb'),
	url(r'^query/$',views.query,name="query"),
	url(r'^analysis/$',views.analysis,name="analysis"),
	]

mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('demo.urls')),
    url(r'^demo/',include('demo.urls')),
]

mysite/demo/models.py
#coding:utf8
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.
@python_2_unicode_compatible
class person(models.Model):
	user_name=models.CharField(u'用户名',max_length=100)
	password=models.CharField(u'密码',max_length=100)
	email=models.CharField(u'邮箱',max_length=20)
	def __str__(self):
		return self.user_name
@python_2_unicode_compatible
class Item(models.Model):
	name=models.CharField(u'项目名称',max_length=100)
	time=models.CharField(u'中标时间',max_length=40)
	company=models.CharField(u'中标公司',max_length=100)
	money=models.FloatField(u'中标金额')
	def __str__(self):
		return self.name
@python_2_unicode_compatible
class Web(models.Model):
	webAddr=models.CharField(max_length=100)
	def __str__(self):
		return self.webAddr

mysite/demo/forms.py
from django import forms


class WebForm(forms.Form):
	webfile = forms.FileField()

mysite/demo/views.py
#-*-coding:utf8-*-
from __future__ import print_function
from django.shortcuts import render,redirect,render_to_response
from django.http import HttpResponse,HttpResponseRedirect
from .models import person,Web,Item
from .forms import WebForm
import sys
from . import province
from . import data_analysis
from . import verifycode
# Create your views here.
#reload(sys)
#sys.setdefaultencoding('utf8')

#登陆界面函数
def index(request,num=0):
	request.session.set_test_cookie()
	if(request.session.test_cookie_worked()):
		request.session.delete_test_cookie()
		request.session['verifycode']=verifycode.photo_create()
		request.session.set_expiry(0)
		dic={0:u'账户',1:u'账号信息错误',2:u'验证码错误',3:u'用户未登录'}
		return render(request,'demo\index.html',{'account':dic[num]})
	else: 
		return HttpResponse('please enable the cookie')

#提交登录表单时的函数
def login(request):
	if(request.method=="POST"):
		#验证码是否正确
		if(request.session['verifycode']==request.POST['verifycode']):
			user=person.objects.filter(user_name=request.POST['username'])
			#用户名与密码是否正确
			if(user and user[0].password==request.POST['password']):
				request.session['username']=user[0].user_name
				request.session['password']=user[0].password
				#redirect到系统界面
				return redirect('demo:system')
			else:
				return index(request,1)
		else:
			return index(request,2)
	else:
		return redirect('demo:index')

#进入系统管理界面
def system(request):
	if(request.session.get('username')):
		username=request.session['username']
		return render(request,'demo\system.html',{'username':username,'adminurl':"http://localhost:8000/admin"})
	else:
		return index(request,3)
def logout(request):
	if(request.session.get('username')):
		request.session.flush()
		return render(request,'demo\logout.html')
	else:
		return redirect('demo:index')

#进度条函数
begin_crap=0#是否开始抓取,初始化进度条,0为开始 1开始 2结束
web=''
def craptimer(request):
	global timer,web
	if(begin_crap==0):
		return HttpResponse('grap not begin')
	elif(begin_crap==2):
		return HttpResponse('grap end,some web can not be grapped')
	else:	
		return render(request,'demo\craptimer.html',{'website':web,'x':int(province.per)})
#网页抓取函数
web_to_crapper=[]
def crap(request):
	global web_to_crapper,begin_crap
	begin_crap=0
	province.per=0.0
	if(request.session.get('username')):
		username=request.session['username']
		if(request.method=="GET"):
			website_list=Web.objects.all()#数据库内存入的网址
			return render(request,'demo\webcrap.html',{'status1':'block','status2':'none','website_list':website_list})
		elif(request.method=="POST"):
			web_key=request.POST.get('web_to_crapper',0)
			if(web_key==0):
				pass
			else:
				web_to_crapper=web_key.split('*')
				print(web_to_crapper)
				return render(request,'demo\webcrap.html',{'status1':'none','status2':'block','website_list':[]})
			#province.Page()
	else:
		return index(request,3)
#因为要先把进度条显示出来才能抓取，所以又定义了此函数，开始抓取
website_dict={'http://clkg.gzcz.gov.cn/home/list-1153531755759540.html':province.Page,}
def crap_begin(request):
	province.per=0.0
	global web,web_to_crapper,begin_crap
	web=""
	begin_crap=1
	print("begin")
	for web_temp in web_to_crapper:
		if website_dict.get(web_temp):
			web=web_temp
			website_dict[web_temp]()
	begin_crap=2
	province.per=0.0
	return render(request,'demo\webcrap.html',{'status1':'none','status2':'block','website_list':[]})

def upweb(request):
	if request.method =='POST':
		if 'sub' in request.POST:
			wf = WebForm(request.POST,request.FILES)
			
			if wf.is_valid():
				destination = open('demo/upload/webfile.txt', 'wb+')
				f = request.FILES['webfile']
				for chunk in f.chunks():
					destination.write(chunk)
				destination.close()
				webfp = open("demo/upload/webfile.txt",'r')
				webAddr = webfp.readlines()
				return render(request,'demo/website.html',{'objects': webAddr})

		else:
				key=request.POST.get('webaddr')
				st=""
				for ch in key:
					if ch=='*':
						Web.objects.create(webAddr=st)
						st=""
					else:
						st=st+ch
				return redirect('demo:upweb')

	else:
		wf = WebForm()
	return render(request,'demo/website.html',{})


def query(request):
	if(request.session.get('username')):
		if (request.method=='POST'):
			way_list=request.POST.getlist('way')
			result=Item.objects.all()
			for way in way_list:
				if(way=='name'):
					result=result.filter(name=request.POST.get('name',''))
				if(way=='company'):
					result=result.filter(company=request.POST.get('company',''))
				if(way=='time'):
					result=result.filter(time__range=(request.POST.get('data_begin',''),request.POST.get('data_end','')))
				if(way=='money'):
					result=result.filter(money__range=(request.POST.get('money_begin',''),request.POST.get('money_end','')))
			return render(request,'demo/dataquery.html',{'table_list':result,'status1':'block'})
		else:
			return render(request,'demo/dataquery.html',{'table_list':[],'status1':'none'})
	else:
		return index(request,3)


#数据分析函数
def analysis(request):
	if(request.session.get('username')):
		if(request.method=="POST"):
			if(request.POST.get('name')):
				t=request.POST.get('name')
				#data_analysis.analysis1(t)
				data_analysis.analysis2(t)
				return render(request,'demo/data_analysis.html',{'dict_list':{}})
			elif(request.POST.get('time_begin')):
				dic={}
				Item_list=Item.objects.filter(time__range=(request.POST.get('time_begin',''),request.POST.get('time_end','')))
				for i in Item_list:
					if(not dic.get(i.company)):
						dic[i.company]=i.money
					else:
						dic[i.company]=dic[i.company]+i.money
				return render(request,'demo/data_analysis.html',{'dict_list':dic})
			else:
				return render(request,'demo/data_analysis.html',{'dict_list':{}})
		else:
			return render(request,'demo/data_analysis.html',{'dict_list':{}})
	else:
		return index(request,3)

mysite/demo/templates/demo/craptimer.html
<!DOCTYPE html>
<html>
<head>
   <title>Bootstrap 实例 - 进度条</title>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   <link href="../../static/demo/css/bootstrap.min.css" rel="stylesheet">
   <script src="../../static/demo/js/jquery.min.js"></script>
   <script src="../../static/demo/js/bootstrap.min.js"></script>
</head>
<body>
   <div>
      <p>正在解析<br>{{website}}</p>
   </div>
<div class="progress">
   <div class="progress-bar" role="progressbar" aria-valuenow="60" 
      aria-valuemin="0" aria-valuemax="100" style="width:{{x}}%">
      <span class="sr-only"></span>
      <p style="color:black">{{x}}%完成</p>
   </div>
</div>
<script>
function myrefresh() 
{ 
window.location.reload(); 
} 
setTimeout('myrefresh()',1000); //指定1秒刷新一次
</script>
</body>
</html>			

mysite/demo/templates/demo/data_analysis.html
<!DOCTYPE html>
<html>
<head>
   <title></title>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   <link href="../../static/demo/css/bootstrap.min.css" rel="stylesheet">
   <script src="../../static/demo/js/jquery.min.js"></script>
   <script src="../../static/demo/js/bootstrap.min.js"></script>
</head>
<body>
<div>
   <label>指定中标单位历史中标金额数据趋势</label>
   <form class="form-horizontal" role="form" action={%url 'demo:analysis'%} method='POST'>
   <label>公司名称</label>
      <input type='text' class="form-control" id="name" name="name"
            placeholder="例：北京红亚华宇科技有限公司" style="width:200px">
      <button type="submit" class="btn btn-success btn-xs">查询</button>
   </form>
   <br>
   <label>直方图</label>
   <br>
   <img src="../../static/demo/images/bar.png" alt="" Width="400px" Height="200px"/>
</div>
<div>
   <label>各中标单位指定时间范围内的中标金额汇总数据</label>
   <form class="form-horizontal" role="form" action={%url 'demo:analysis'%} method='POST'>
   <label>起始时间</label>
      <input type='text' class="form-control" id="time_begin" name="time_begin"
            placeholder="例：2013-12-15" style="width:200px">
      <label>终止时间</label>
      <input type='text' class="form-control" id="time_end" name="time_end"
            placeholder="例：2014-12-15" style="width:200px">
      <button type="submit" class="btn btn-success btn-xs">查询</button>
   </form>
   <table class="table table-striped">
      <thead><th>公司名称</th><th>金额汇总数据</th></thead>
      <tbody>
         {% for key,value in dict_list.items %}
         <tr><td>{{key}}</td><td>{{value}}</td></tr>
         {%endfor%}
      </tbody>
   </table>
</div>
<script>

</script>
</body>
</html>			

mysite/demo/templates/demo/dataquery.html
<!DOCTYPE html>
<html>
<head>
   <title></title>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   <link href="../../static/demo/css/bootstrap.min.css" rel="stylesheet">
   <script src="../../static/demo/js/jquery.min.js"></script>
   <script src="../../static/demo/js/bootstrap.min.js"></script>
</head>
<body>
   <div>
      <form class="form-horizontal" role="form" action={%url 'demo:query'%} method="POST">
         <label>项目名称</label>
         <input type="text" class="form-control" id="name" name="name"
            placeholder="例：无人机及信息安全平台设备采购" style="width:200px">
         <label>中标单位</label>
         <input type="text" class="form-control" id="company" name="company" 
            placeholder="例：北京红亚华宇科技有限公司" style="width:200px">
         <label>最小中标金额</label>
         <input type="text" class="form-control" id="lastname" name="money_begin"
            placeholder="例：12345.0" style="width:200px">
         <label>最大中标金额</label>
         <input type="text" class="form-control" id="lastname" name="money_end"
            placeholder="例：22223.0" style="width:200px">
         <label>起始中标时间</label>
         <input type="text" class="form-control" id="lastname" name="data_begin"
            placeholder="例：2013-12-15" style="width:200px">
         <label>终止中标时间</label>
         <input type="text" class="form-control" id="lastname" name="data_end"
            placeholder="例：2014-12-15" style="width:200px">
         <label>查询方式(可多选)</label><br/>
         <input type="checkbox" value="name" name="way">项目名称<br/>
         <input type="checkbox" value="company" name="way">中标单位<br/>
         <input type="checkbox" value="money" name="way">中标金额范围<br/>
         <input type="checkbox" value="time" name="way">中标时间范围<br/>
         <button type="submit" class="btn btn-success btn-xs">查询</button>
      </form>
   </div>
   <div style="display:{{status1}}">
      <table class="table table-striped">
      <thead><th>项目名称</th><th>中标单位</th><th>中标金额</th><th>中标时间</th></thead>
      <tbody>
      {%for list in table_list%}
      <tr><td>{{list.name}}</td><td>{{list.company}}</td><td>{{list.money}}</td><td>{{list.time}}</td></tr>
      {%endfor%}
      </tbody>
      </table>
   </div>
<script>
</script>
</body>
</html>			

mysite/demo/templates/demo/logout.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../static/demo/images/nuaa.ico">

    <title>退出登录</title>

    <!-- Bootstrap core CSS -->
    <link href="../../static/demo/css/bootstrap.min.css" rel="stylesheet">
    </head>
<body>
<p>您已退出登录</p>
<hr>
<a href={%url 'demo:index'%}> 返回首页</a>
</body>
</html>

mysite/demo/templates/demo/system.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../static/demo/images/nuaa.ico">

    <title>采购信息查询</title>

    <!-- Bootstrap core CSS -->
    <link href="../../static/demo/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <style type="text/css">
    /* Custom Styles */
    ul.nav-tabs{
        width: 140px;
        margin-top: 20px;
        border-radius: 4px;
        border: 1px solid #ddd;
        box-shadow: 0 1px 4px rgba(0, 0, 0, 0.067);
    }
    ul.nav-tabs li{
        margin: 0;
        border-top: 1px solid #ddd;
    }
    ul.nav-tabs li:first-child{
        border-top: none;
    }
    ul.nav-tabs li a{
        margin: 0;
        padding: 8px 16px;
        border-radius: 0;
    }
    ul.nav-tabs li.active a, ul.nav-tabs li.active a:hover{
        color: #fff;
        background: #0088cc;
        border: 1px solid #0088cc;
    }
    ul.nav-tabs li:first-child a{
        border-radius: 4px 4px 0 0;
    }
    ul.nav-tabs li:last-child a{
        border-radius: 0 0 4px 4px;
    }
    ul.nav-tabs.affix{
        top: 30px; /* Set the top position of pinned element */
    }
</style>
  </head>

  <body data-spy="scroll" data-target="#myScrollspy">
<div class="container">
  <div class="jumbotron" style="background-color:#99CCFF;color:white">
        <h1>采购信息查询</h1>
        <div class="row">
        <div class="col-xs-9">
        </div>
        <div class="col-xs-3">
        <ul class="nav nav-pills" style="font-size:20px">
        <li class="active"><a href="#">主页</a></li>
        <li><a href="#">帮助</a></li>
        <li><a href={%url 'demo:logout'%}>退出</a></li>
        </ul>
        </div>
        </div>
    </div> 
    <div class="row">
        <div class="col-xs-3" id="myScrollspy">
            <ul class="nav nav-tabs nav-stacked" data-spy="affix" data-offset-top="125">
                <li class="active"><a href="#">系统功能</a></li>
                <li><a href="#section-1">网址配置</a></li>
                <li><a href="#section-2">网页抓取</a></li>
                <li><a href="#section-3">分类查询</a></li>
                <li><a href="#section-4">数据统计</a></li>
            </ul>
        </div>
        <div class="col-xs-9">
            <h2 id="section-1">网址配置</h2>
            <h3>上传包含您要爬取的网址的.txt文件我们将会自动爬取该网址</h3>
            <iframe src={%url 'demo:upweb'%} name="iframe_1" frameborder='0' width="800px" height="600px"></iframe>
            <hr>
            <h2 id="section-2">网页抓取</h2>
             <button class="btn btn-success btn-xs" onclick="refresh()">查看可抓取的网页</button>
            <iframe src={%url 'demo:crap' %} name="iframe_2" id="iframe_2" frameborder='0' width="800px" height="800px"></iframe> 
            <hr>
            <h2 id="section-3">分类查询</h2>
            <p></p>
            <iframe src={%url 'demo:query'%} name="iframe_3" frameborder='0' width="800px" height="600px"></iframe>
            <hr>
            <h2 id="section-4">数据统计</h2>
             <p></p>
             <iframe src={%url 'demo:analysis'%} name="iframe_4" frameborder='0' width="800px" height="800px"></iframe>
            <hr>
        </div>
    </div>
</div>
    <!-- /.container -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../../static/demo/js/jquery.min.js"></script>
    <script src="../../static/demo/js/bootstrap.min.js"></script>
    <script type="text/JavaScript">
    function refresh(){
        var d=document.getElementById("iframe_2")
        d.src="{%url 'demo:crap'%}"
    }
    </script>
  </body>
</html>

mysite/demo/templates/demo/webcrap.html
<!DOCTYPE html>
<html>
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   <link href="../../static/demo/css/bootstrap.min.css" rel="stylesheet">
   <script src="../../static/demo/js/jquery.min.js"></script>
   <script src="../../static/demo/js/bootstrap.min.js"></script>
</head>
<body>
   <div style="display:{{status1}}">
   <table class="table table-striped" id="td1">
   <thead>
   		<th>网址</th><th></th>
   	</thead>
   	<tbody>
      {% for web in website_list %}
      <tr><td>{{web}}</td><td><button onclick="select(this)" class="btn btn-success btn-xs">选择</button></td></tr>
      {% endfor %}
      </tbody>
   </table>
   <button onclick="select_all()" class="btn btn-success btn-xs">全选</button>
   </div>
   <div style="display:{{status1}}">
   <table class="table table-striped">
   <thead>
      <th>将要进行爬取的网址</th>
   </thead>
   <tbody id="td">
   </tbody>
   </table>
   <button onclick="del()" class="btn btn-success btn-xs">取消</button>&nbsp&nbsp&nbsp&nbsp<button class="btn btn-success btn-xs" onclick="submit_array()">确认</button>&nbsp&nbsp&nbsp&nbsp</div>
   <iframe id="iframe1" name="iframe1" src={% url 'demo:craptimer'%} style="display:{{status2}};width:600px" ></iframe>
   <hr>
   <a href={%url 'demo:crap_begin'%}><button class="btn btn-success btn-xs" style="display:{{status2}}" onclick="begin_crap()">开始抓取</button></a>
<script type="text/javascript">
	web_to_crap=new Array();
   i=0;
   function select(obj)
   {
	var f=obj.parentNode.previousSibling;
   web_to_crap[i]=f.innerHTML;
   var g=document.getElementById('td');
   var r=g.insertRow(i);
   var d=r.insertCell(0);
   d.innerHTML=f.innerHTML;
   i++;
   //alert("this is a test");
	}
   function del(obj)
   {
      var t=document.getElementById('td');
      t.innerHTML=null;
      web_to_crap=[];
      i=0;
      //alert("delete sucess");
   }
   function select_all(){
      var t=document.getElementById("td1").rows;
      var count=0;
      var g=document.getElementById("td");
      g.innerHTML=null;
      for(i=1;i<t.length;i++){
         web_to_crap[count]=t[i].firstChild.innerHTML;
         var r=g.insertRow(count);
         var d=r.insertCell(0);
         d.innerHTML=web_to_crap[count];
         count++;
      }
      i=count;
      //alert("全选成功");
   }
   function submit_array(){
    var myForm = document.createElement("form"); 
    myForm.method="post" ; 
    myForm.action = "{% url 'demo:crap'%}" ; 
    var myInput = document.createElement("input") ; 
    myInput.name="web_to_crapper" ;
    if(web_to_crap.length==0){
      alert("不能为空")
      return
    } 
    for(i=0;i<web_to_crap.length;i++){
      myInput.value=myInput.value+web_to_crap[i]+"*"
    }
    myForm.appendChild(myInput) ;
    document.body.appendChild(myForm) ; 
    myForm.submit() ; 
    document.body.removeChild(myForm) 
   }
   function begin_crap(){
    iframe_temp=document.getElementById('iframe1');
    iframe_temp.src={% url 'demo:craptimer'%}
   }
</script>
</body>
</html>			

mysite/demo/templates/demo/website.html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<script type="text/javascript" src="../../static/demo/js/jquery.min.js"></script>
<!--<script type="text/javascript" src="http://www.francescomalagrino.com/BootstrapPageGenerator/3/js/jquery-ui"></script>-->
<link href="../../static/demo/css/bootstrap.min.css" rel="stylesheet" media="screen">
<script type="text/javascript" src="../../static/demo/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
	<div class="row-fluid">


			<form method="POST" enctype="multipart/form-data" name="webfile">
				<fieldset>
					<legend></legend>
					<label>文件上传</label><br>
					 <input type="file" name="webfile" /><br/>
					 <input type="submit" value="提交" name="sub" onclick="document.webfile.submit()" class="btn btn-success btn-xs" />
				</fieldset>	
			</form>

				<fieldset>
				<legend>网址预览</legend>
					<table id ="website" name="webtable" class="table table-striped">
					<tr><td>website</td><td>operation</td></tr>

						{% for object in objects %}
							<tr><td>{{ object }}</td>
							<td><input type="button" value="修改"/ onclick="change(this)" class="btn btn-success btn-xs">
							<input type="button" value="确定"/ onclick="sure(this)" class="btn btn-success btn-xs"></td></tr>
						{% endfor %}
					</table><br/>
					<input type="button" value="保存网址" name="save" onclick="save(this)" class="btn btn-success btn-xs"/>
				</fieldset>

	</div>
</div>
</body>

<script type="text/javascript">

function sure(su){
var table4=document.getElementById("website").rows;
var rowss=su.parentNode.parentNode.rowIndex;
var cellss=table4[rowss].cells[0];
cellss.innerHTML=document.getElementById("id1").value;

}
function change(ch){
var table3=document.getElementById("website").rows;
var rowss=ch.parentNode.parentNode.rowIndex;
var cellss=table3[rowss].cells[0];
var oldR=cellss.innerHTML;
cellss.innerHTML="<input type='text' id='id1' > ";
document.getElementById("id1").value=oldR;
}

function save(sa){

	var tab =document.getElementById("website");	
	var SaObj = document.createElement("form");		
	var rows=tab.rows;
	var opt = document.createElement("input");
	opt.name = "webaddr";
	for(i =1;i<rows.length;i++){
		opt.value = opt.value +tab.rows[i].cells[0].innerHTML+"*";
	}
	SaObj.appendChild(opt);
	SaObj.method="POST";
	SaObj.name = "website"
	SaObj.submit();

	return SaObj;
}

</script>

</html>